# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aacff394e916a1a7bb0ab8a7696ffee478ee705173cace70a95771bf060564830f2f8479c8e9df2e6c5272741e10ca5bb07d345b08e8e02d1354a0e013395606

test:
  secret_key_base: d789ffa8e5e517fcc64a0adcc5455be6d065e0440a6f3711496bbf0a71a80fbd8cd44d1281511850e4d97016a167f84fda68da2f89529af2492ae39f45293d03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
